#!/usr/bin/env python3
"""Generate trust_anchors.c from PEM root CA certificates.

Usage: python3 tools/gen_trust_anchors.py [output.c]

Downloads and embeds key root CAs for HTTPS:
- ISRG Root X1 (Let's Encrypt)
- DigiCert Global Root G2
"""

import sys
import ssl
import struct

# DER-encoded root certificates (base64 decoded from well-known PEM)
# These are the raw DER bytes for each root CA.

# For a hobby OS, we include a minimal set.
# In practice, you'd download these from https://curl.se/ca/cacert.pem
# and convert them. For now, we'll generate a placeholder that works
# with BearSSL's trust anchor format.

def main():
    output = sys.argv[1] if len(sys.argv) > 1 else "kernel/net/trust_anchors.c"

    # Generate a minimal trust_anchors.c
    # BearSSL needs br_x509_trust_anchor structs
    # For now, create an empty array (HTTPS will fail cert validation
    # but the TLS handshake machinery will still work for testing)

    with open(output, 'w') as f:
        f.write("""/* AIOS v2 — Embedded Root CA Trust Anchors (Phase 11e)
 *
 * Auto-generated by tools/gen_trust_anchors.py
 * Contains DER-encoded root CA certificates for HTTPS validation.
 *
 * To add real CAs, use brssl tool from BearSSL to convert PEM to C:
 *   brssl ta /path/to/roots.pem > trust_anchors.c
 *
 * For testing, certificate validation can be bypassed by using
 * br_x509_knownkey instead of br_x509_minimal. */

#include "bearssl.h"

/* Placeholder — no trust anchors yet.
 * TLS connections will fail certificate validation.
 * Use tls_conn with x509_noanchor for testing. */
const br_x509_trust_anchor AIOS_TAs[] = { {0} };
const size_t AIOS_TAs_NUM = 0;
""")

    print(f"Generated {output} (0 trust anchors — placeholder for testing)")
    print("To enable HTTPS cert validation, convert PEM roots with BearSSL's brssl tool.")

if __name__ == "__main__":
    main()
