#!/usr/bin/env python3
"""Generate BearSSL trust anchors C file from Mozilla CA bundle.

Downloads cacert.pem from curl.se, parses each root certificate,
extracts the DN and public key, and generates trust_anchors.c
in BearSSL's br_x509_trust_anchor format.

Usage: python3 tools/gen_trust_anchors.py [output_file]
Requires: python-cryptography (pacman -S python-cryptography)
"""

import sys
import os
import re
import base64
import subprocess

PEM_URL = "https://curl.se/ca/cacert.pem"
PEM_CACHE = "/tmp/cacert.pem"
OUTPUT = sys.argv[1] if len(sys.argv) > 1 else "kernel/net/trust_anchors.c"


def download_bundle():
    """Download Mozilla CA bundle if not cached."""
    if os.path.exists(PEM_CACHE) and os.path.getsize(PEM_CACHE) > 10000:
        return
    print(f"Downloading {PEM_URL}...")
    subprocess.check_call(["curl", "-sL", PEM_URL, "-o", PEM_CACHE])


def bytes_to_c(data, name):
    """Convert bytes to a C static const unsigned char array."""
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("};")
    return "\n".join(lines)


def main():
    from cryptography import x509
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa, ec

    download_bundle()

    with open(PEM_CACHE, 'r') as f:
        pem_data = f.read()

    cert_pems = re.findall(
        r'-----BEGIN CERTIFICATE-----\n(.+?)\n-----END CERTIFICATE-----',
        pem_data, re.DOTALL)
    print(f"Found {len(cert_pems)} certificates")

    ta_entries = []
    data_blocks = []
    idx = 0

    for pem_b64 in cert_pems:
        der = base64.b64decode(pem_b64.replace('\n', ''))
        try:
            cert = x509.load_der_x509_certificate(der)
        except Exception as e:
            continue

        dn_der = cert.subject.public_bytes(serialization.Encoding.DER)
        pub_key = cert.public_key()

        dn_name = f"dn{idx}"
        data_blocks.append(bytes_to_c(dn_der, dn_name))

        if isinstance(pub_key, rsa.RSAPublicKey):
            nums = pub_key.public_numbers()
            n = nums.n.to_bytes((nums.n.bit_length() + 7) // 8, 'big')
            e = nums.e.to_bytes((nums.e.bit_length() + 7) // 8, 'big')
            n_name, e_name = f"rn{idx}", f"re{idx}"
            data_blocks.append(bytes_to_c(n, n_name))
            data_blocks.append(bytes_to_c(e, e_name))
            ta_entries.append(
                f"    {{ {{ (unsigned char *){dn_name}, sizeof({dn_name}) }}, "
                f"BR_X509_TA_CA, {{ BR_KEYTYPE_RSA, "
                f"{{ .rsa = {{ (unsigned char *){n_name}, sizeof({n_name}), "
                f"(unsigned char *){e_name}, sizeof({e_name}) }} }} }} }}")

        elif isinstance(pub_key, ec.EllipticCurvePublicKey):
            q = pub_key.public_bytes(
                serialization.Encoding.X962,
                serialization.PublicFormat.UncompressedPoint)
            curve = pub_key.curve
            if isinstance(curve, ec.SECP256R1): cid = "BR_EC_secp256r1"
            elif isinstance(curve, ec.SECP384R1): cid = "BR_EC_secp384r1"
            elif isinstance(curve, ec.SECP521R1): cid = "BR_EC_secp521r1"
            else: continue
            q_name = f"eq{idx}"
            data_blocks.append(bytes_to_c(q, q_name))
            ta_entries.append(
                f"    {{ {{ (unsigned char *){dn_name}, sizeof({dn_name}) }}, "
                f"BR_X509_TA_CA, {{ BR_KEYTYPE_EC, "
                f"{{ .ec = {{ {cid}, (unsigned char *){q_name}, sizeof({q_name}) }} }} }} }}")
        else:
            continue

        idx += 1

    print(f"Generated {idx} trust anchors")

    with open(OUTPUT, 'w') as f:
        f.write(f"/* AIOS Trust Anchors — Mozilla CA Bundle ({idx} roots)\n")
        f.write(f" * Auto-generated by tools/gen_trust_anchors.py\n")
        f.write(f" * Source: {PEM_URL} */\n\n")
        f.write('#include "bearssl.h"\n\n')
        for block in data_blocks:
            f.write(block + "\n\n")
        f.write(f"static const br_x509_trust_anchor AIOS_TA_LIST[] = {{\n")
        f.write(",\n".join(ta_entries))
        f.write(f"\n}};\n\n")
        f.write(f"const br_x509_trust_anchor *AIOS_TAs = AIOS_TA_LIST;\n")
        f.write(f"const size_t AIOS_TAs_NUM = {idx};\n")

    size = os.path.getsize(OUTPUT)
    print(f"Written to {OUTPUT} ({size // 1024} KB)")


if __name__ == '__main__':
    main()
